---
- hosts: all
  tasks:

    - name: Instalar apache y php
      yum:
        name:
          - httpd
          - php
          - php-mysql

    - name: Iniciar Apache
      systemd:
        state: started
        name: httpd
        enabled: yes

  become: true
  become_user: root
